### ISSUE TITLE
Compilation of type.cxx fails

### ISSUE THREAD

**Issue by mgrantley** [hanya/RUNO#9]
Using Ruby 1.9.3, Openoffice3.4 on Ubuntu complation of type.cxx fails with following error messages:

`type.cxx: In function ‘void rubyuno::raise_rb_exception(const com::sun::star::uno::Any&)’:
type.cxx:340:83: error: format not a string literal and no format arguments [-Werror=format-security]
   rb_raise(klass, OUStringToOString(e.Message, RTL_TEXTENCODING_ASCII_US).getStr());
                                                                                   ^
cc1plus: some warnings being treated as errors
make: *** [type.o] Error 1`

Not sure whether or not this error should be skipped by manually changing the Makefile and ignoring that warning.

**Comment by hanya** [comment]
Thanks for reporting. I pushed the fix.
